import type { LanguageOption, AnalysisTopic, StyleGuideOption } from './types';

export const LANGUAGES: LanguageOption[] = [
    { code: 'en', name: 'English', flag: '🇬🇧' },
    { code: 'pt', name: 'Português', flag: '🇧🇷' },
    { code: 'es', name: 'Español', flag: '🇪🇸' },
    { code: 'fr', name: 'Français', flag: '🇫🇷' },
];

export const AVAILABLE_MODELS: {name: string, description: string}[] = [
    { name: 'gemini-2.5-flash', description: 'Fast and efficient for most tasks.' },
    { name: 'gemini-2.5-pro', description: 'More powerful for complex generation and reasoning.' },
    { name: 'grok-4-latest', description: 'Powerful model from x.ai.' },
];

export const STYLE_GUIDES: StyleGuideOption[] = [
    { key: 'abnt', name: 'ABNT', description: 'Associação Brasileira de Normas Técnicas NBR 6023' },
    { key: 'apa', name: 'APA', description: 'American Psychological Association 7th Edition' },
    { key: 'mla', name: 'MLA', description: 'Modern Language Association 9th Edition' },
    { key: 'ieee', name: 'IEEE', description: 'Institute of Electrical and Electronics Engineers' },
];

// Optimized list of 15 essential analysis topics
export const ANALYSIS_TOPICS: AnalysisTopic[] = [
    { num: 1, name: 'TOPIC FOCUS', desc: 'Maintains the central argument without deviation.' },
    { num: 2, name: 'CLARITY AND PRECISION', desc: 'Quality of scientific writing, including grammar, clarity, and correct use of terminology.' },
    { num: 3, name: 'STRUCTURE AND COHERENCE', desc: 'Logical flow and organization of the paper, with smooth transitions between sections.' },
    { num: 4, name: 'CORE COMPONENTS (TITLE, ABSTRACT, INTRO, CONCLUSION)', desc: 'Effectiveness of the title, abstract, introduction, and conclusion as stand-alone and integrated parts.' },
    { num: 5, name: 'LITERATURE REVIEW', desc: 'Quality of the literature review in establishing context, theoretical foundation, and identifying the research gap.' },
    { num: 6, name: 'METHODOLOGY (RIGOR AND CLARITY)', desc: 'Scientific rigor and clarity of the methodology, ensuring the study is sound and replicable.' },
    { num: 7, name: 'RESULTS PRESENTATION', desc: 'Clarity and logical organization of the results section.' },
    { num: 8, name: 'DISCUSSION AND ANALYSIS', desc: 'Depth of interpretation, critical analysis, and discussion of practical implications.' },
    { num: 9, name: 'ARGUMENTATION STRENGTH', desc: 'Logical soundness of arguments and the evidence supporting them.' },
    { num: 10, name: 'ORIGINALITY AND CONTRIBUTION', desc: 'Novelty and significance of the paper’s contribution to the field.' },
    { num: 11, name: 'SCOPE AND LIMITATIONS', desc: 'Clear definition of the research scope and honest acknowledgment of its limitations.' },
    { num: 12, name: 'SCIENTIFIC CONTENT ACCURACY', desc: 'Correctness of scientific information, data, and claims presented.' },
    { num: 13, name: 'REFERENCES AND CITATIONS', desc: 'Quality, relevance, and correct formatting of references and in-text citations.' },
    { num: 14, name: 'LATEX TECHNICAL ACCURACY', desc: 'Verification of LaTeX formatting to prevent compilation issues.' },
    { num: 15, name: 'PAGE COUNT COMPLIANCE', desc: 'Verifies that the generated paper meets the requested number of pages.' }
];


// Fix: Add FIX_OPTIONS to be exported for use in FixModal.tsx
export const FIX_OPTIONS: { key: string; label: string; description: string }[] = [
    {
        key: 'escape_chars',
        label: 'Fix Character Escaping',
        description: 'Scans the document for special LaTeX characters (like %, $, _, &) that were not correctly escaped and fixes them.'
    },
    {
        key: 'citation_mismatch',
        label: 'Fix Citation Mismatches',
        description: 'Ensures that every \\cite{...} command in the text has a corresponding \\bibitem entry in the bibliography, and vice-versa.'
    },
    {
        key: 'preamble_check',
        label: 'Verify Preamble',
        description: 'Checks if the document preamble uses only the allowed packages in the correct order as specified by the generation rules.'
    },
    {
        key: 'page_margin_overflow',
        label: 'Fix Page Margin Overflows',
        description: 'Analyzes the document for text, URLs, or other content that exceeds the page margins (overfull \\hbox) and rewrites it to fit. This may involve rephrasing sentences, breaking long words or identifiers, or using LaTeX commands like \\sloppy or \\url{} to improve line breaking.'
    }
];

export const MATH_TOPICS: string[] = [
    'Fundamentos da Matemática',
    'Lógica Matemática',
    'Proposições e conectivos lógicos',
    'Tabelas-verdade e equivalências',
    'Argumentos e deduções válidas',
    'Quantificadores (∀, ∃)',
    'Teoria dos predicados',
    'Sistemas formais e provas',
    'Lógica de primeira e segunda ordem',
    'Lógica modal, temporal e intuicionista',
    'Teoria dos Conjuntos',
    'Conjuntos e operações (união, interseção, complemento)',
    'Relações e funções',
    'Cardinalidade e infinitos (enumerável, não enumerável)',
    'Conjuntos numéricos (ℕ, ℤ, ℚ, ℝ, ℂ)',
    'Paradoxo de Russell',
    'Axiomas de Zermelo–Fraenkel (ZF e ZFC)',
    'Ordinais e cardinais transfinitos',
    'Teoria dos Números Fundamentais',
    'Números naturais, inteiros, racionais, irracionais e reais',
    'Axiomas de Peano',
    'Indução e recursão',
    'Sistemas de numeração',
    'Aritmética modular',
    'Álgebra',
    'Álgebra Elementar',
    'Expressões algébricas',
    'Equações e inequações',
    'Polinômios e fatoração',
    'Funções e gráficos (lineares, quadráticas, racionais, exponenciais, logarítmicas)',
    'Sistemas lineares',
    'Álgebra Linear',
    'Vetores e espaços vetoriais',
    'Combinações lineares e dependência',
    'Matrizes e determinantes',
    'Transformações lineares',
    'Autovalores e autovetores',
    'Diagonalização e formas canônicas',
    'Produtos internos e ortogonalização',
    'Álgebra Abstrata (Moderna)',
    'Estruturas algébricas: grupos, anéis e corpos',
    'Homomorfismos e isomorfismos',
    'Subgrupos normais e grupos quocientes',
    'Ideais e anéis fatoriais',
    'Corpos finitos e extensões de corpos',
    'Espaços vetoriais sobre corpos finitos',
    'Teoremas de Lagrange, Cauchy e Sylow',
    'Álgebra comutativa e teoria dos módulos',
    'Geometria',
    'Geometria Plana',
    'Pontos, retas, ângulos e triângulos',
    'Semelhança e congruência',
    'Circunferência e polígonos regulares',
    'Teorema de Pitágoras',
    'Áreas e perímetros',
    'Geometria Espacial',
    'Poliedros, prismas e pirâmides',
    'Cilindros, cones e esferas',
    'Volume e área superficial',
    'Geometria Analítica',
    'Coordenadas cartesianas',
    'Retas, planos e distâncias',
    'Cônicas: circunferência, elipse, parábola e hipérbole',
    'Vetores e ângulos no espaço',
    'Transformações geométricas',
    'Geometria Diferencial',
    'Curvas e superfícies suaves',
    'Curvatura e torção',
    'Variedades diferenciáveis',
    'Campos vetoriais e formas diferenciais',
    'Geometria Projetiva e Não-Euclidiana',
    'Homogeneização de coordenadas',
    'Geometria hiperbólica e elíptica',
    'Modelos de Poincaré e Riemann',
    'Cálculo e Análise Matemática',
    'Pré-Cálculo',
    'Limites e continuidade',
    'Funções e suas propriedades',
    'Cálculo Diferencial',
    'Derivadas e taxas de variação',
    'Regras de derivação',
    'Derivadas parciais e gradiente',
    'Máximos e mínimos',
    'Cálculo Integral',
    'Integrais indefinidas e definidas',
    'Técnicas de integração',
    'Teorema Fundamental do Cálculo',
    'Integrais impróprias',
    'Cálculo Vetorial e Multivariável',
    'Campos escalares e vetoriais',
    'Integrais de linha e de superfície',
    'Teoremas de Green, Gauss e Stokes',
    'Análise Real',
    'Sequências e séries',
    'Convergência uniforme',
    'Funções contínuas e diferenciáveis',
    'Teoremas de Bolzano-Weierstrass, Heine-Borel e Banach',
    'Análise Complexa',
    'Números complexos e funções holomorfas',
    'Integração complexa (Cauchy)',
    'Séries de potências',
    'Transformação conforme',
    'Análise Funcional',
    'Espaços normados e métricos',
    'Espaços de Banach e Hilbert',
    'Operadores lineares e contínuos',
    'Teoremas de Hahn–Banach, Riesz e Baire',
    'Probabilidade e Estatística',
    'Probabilidade',
    'Espaço amostral e eventos',
    'Probabilidade condicional e independência',
    'Variáveis aleatórias (discretas e contínuas)',
    'Esperança e variância',
    'Distribuições clássicas (Binomial, Poisson, Normal, Exponencial)',
    'Estatística Descritiva',
    'Média, mediana, moda',
    'Desvio padrão e variância',
    'Gráficos e histogramas',
    'Inferência Estatística',
    'Estimadores e testes de hipótese',
    'Intervalos de confiança',
    'Regressão linear e correlação',
    'ANOVA e modelos lineares',
    'Teoria da Informação e Processos Estocásticos',
    'Entropia e informação mútua',
    'Cadeias de Markov',
    'Processos de Poisson e Brownianos',
    'Matemática Aplicada e Computacional',
    'Métodos Numéricos',
    'Aproximação de raízes',
    'Integração e diferenciação numérica',
    'Interpolação e regressão',
    'Erros e estabilidade numérica',
    'Otimização',
    'Programação linear e não linear',
    'Método Simplex',
    'Otimização convexa e dualidade',
    'Algoritmos de gradiente',
    'Equações Diferenciais',
    'EDOs de primeira e segunda ordem',
    'Sistemas lineares de EDOs',
    'Equações diferenciais parciais',
    'Séries de Fourier e transformadas',
    'Computação Matemática',
    'Álgebra computacional',
    'Análise numérica simbólica',
    'Modelagem matemática e simulação',
    'Estruturas e Teorias Avançadas',
    'Topologia',
    'Conjuntos abertos e fechados',
    'Convergência e continuidade topológica',
    'Conectividade e compacidade',
    'Espaços métricos e topológicos',
    'Homotopia e homologia',
    'Teoria das Categorias',
    'Functores e transformações naturais',
    'Limites e colimites',
    'Adjuntos e equivalências de categorias',
    'Teoria dos Números Avançada',
    'Divisibilidade e primalidade',
    'Teorema de Fermat e Euler',
    'Equações diofantinas',
    'Criptografia e curvas elípticas',
    'Combinatória e Teoria dos Grafos',
    'Permutações e combinações',
    'Princípio da inclusão-exclusão',
    'Teoria de Ramsey',
    'Grafos e árvores',
    'Caminhos e ciclos eulerianos/hamiltonianos',
    'Álgebra Linear Avançada',
    'Formas bilineares e quadráticas',
    'Decomposições espectrais',
    'Tópicos em teoria de representação',
    'Matemática Pura e Aplicada Interdisciplinar',
    'Matemática financeira e atuária',
    'Teoria do controle',
    'Pesquisa operacional',
    'Criptografia e segurança da informação',
    'Teoria dos jogos',
    'Matemática física (mecânica, eletromagnetismo, relatividade)',
    'Sistemas dinâmicos e caos',
    'Modelagem biológica e epidemiológica',
];